
-- DROP IF ALREADY EXISTS --
-- DROP DATABASE LIBRARY_MANAGEMENT;
CREATE DATABASE LIBRARY_MANAGEMENT;

USE LIBRARY_MANAGEMENT;

DROP TABLE IF EXISTS `USERS`;
CREATE TABLE `USERS` (
  `USER_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL,
  `IS_ADMIN` BIT(1) NOT NULL,
  PRIMARY KEY (`USER_ID`)
);

DROP TABLE IF EXISTS `BOOKS`;
CREATE TABLE `BOOKS` (
  `BOOK_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `BOOK_NAME` VARCHAR(50) NOT NULL,
  `GENRE` VARCHAR(50) NOT NULL,
  `PRICE` INT NOT NULL,
  PRIMARY KEY (`BOOK_ID`)
);

DROP TABLE IF EXISTS `ISSUED`;
CREATE TABLE `ISSUED` (
  `ISSUED_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT NOT NULL,
  `BOOK_ID` BIGINT NOT NULL,
  `ISSUED_DATE` VARCHAR(20) NOT NULL,
  `RETURN_DATE` VARCHAR(20) NULL,
  `PERIOD` INT NOT NULL,
  `FINE` INT NULL,
  PRIMARY KEY (`ISSUED_ID`)
);

INSERT INTO `USERS` VALUES
(1, "ADMIN", "ADMIN", 1),
(2, "SACHITA", "PWD", 0);

INSERT INTO `BOOKS` VALUES
(1, 'THE GIRL WITH TWO MOUTHS', 'FICTION', 20),
(2, 'WHO LET THE DOGS OUT', 'MYSTERY', 30),
(3, 'HOW MUCH I LOVE YOU','ROMANCE', 35),
(4, 'THE ALIENS ON MOON','SCI-FI', 25),
(5, 'HOW I BECAME THE MR. PRECT', 'AUTO-BIOGRAPHY', 22);